;;; diff-ansi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from diff-ansi.el

(autoload 'diff-ansi-region "diff-ansi" "\
Convert the diff between points BEG and END into an ANSI-diff.

Optional keywords in ARGS.

`:create-buffer'
  When t, create a new buffer for the diff contents and return it.
  Note that the buffer is not made active.

`:preserve-point'
  When t, place the cursor at the relative line offset based on the location
  in the original buffer (this uses a simple method that doesn't ensure
  an exact match for the current line).

Return the buffer used to write data into on success.

(fn BEG END &rest ARGS)")
(function-put 'diff-ansi-region 'important-return-value 'nil)
(autoload 'diff-ansi-buffer "diff-ansi" "\
Create an ANSI-diff buffer from the existing plain-diff buffer." t)
(function-put 'diff-ansi-buffer 'important-return-value 'nil)
(autoload 'diff-ansi-mode "diff-ansi" "\
Enable `diff-ansi' integration.

This is a minor mode.  If called interactively, toggle the `Diff-Ansi
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `diff-ansi-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "diff-ansi" '("diff-ansi-"))

;;; End of scraped data

(provide 'diff-ansi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; diff-ansi-autoloads.el ends here
